language: perl
perl:
- "5.10"
- "5.26"
dist: trusty
sudo: false
install:
- cpanm IO::Socket::SSL
- python -m pip install --user docutils pygments
script:
- grep -E '\w+://\S+' README -o | sort -u | xargs ./skeptica
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
