language: perl
perl:
- "5.10"
- "5.28"
dist: trusty
install:
- cpanm IO::Socket::SSL
- python -m pip install --user pygments restructuredtext-lint
script:
- grep -E '\w+://\S+' README -o | sort -u | xargs ./skeptica
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
