language: perl
dist: xenial
jobs:
  include:
  - perl: "5.10"
    dist: trusty
  - perl: "5.30"
install:
- cpanm IO::Socket::SSL
- python -m pip install --user pygments restructuredtext-lint
script:
- grep -E '\w+://\S+' README -o | sort -u | xargs ./skeptica
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
