language: perl
dist: xenial
jobs:
  include:
  - perl: "5.10"
    dist: trusty
  - perl: "5.30"
before_install:
- if [[ $TRAVIS_DIST = trusty ]]; then if_rstlint=:; fi
install:
- cpanm IO::Socket::SSL
- $if_rstlint python -m pip install --user pygments restructuredtext-lint
script:
- grep -E '\w+://\S+' README -o | sort -u | xargs ./skeptica
- $if_rstlint restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
